root: true
env:
  es2022: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2022
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"
rules:
  indent: ["error", "tab"]
  quotes: ["error", "double"]
  node/no-unsupported-features/es-syntax: off
overrides:
  - files: ["*.json"]
    rules:
      semi: off
      no-unused-expressions: off
